<?xml version="1.0" encoding="utf-8"?><Database Name="Lanovitadb" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=viewt.database.windows.net,1433;Initial Catalog=Lanovitadb;Persist Security Info=False;User ID=viewt;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;TrustServerCertificate=False" SettingsObjectName="ViewMobile.Pediddo.Core.Data.Properties.Settings" SettingsPropertyName="cangoruadbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Advice" Member="Advices">
    <Type Name="Advice">
      <Column Name="AdviceId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IsPublic" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BuyerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Vip" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Credit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Call" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Body" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="AppImageId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PictureName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Argument" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Highlight" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Advice_AdviceButton" Member="AdviceButtons" ThisKey="AdviceId" OtherKey="AdviceId" Type="AdviceButton" />
      <Association Name="Advice_BuyerAdviceLog" Member="BuyerAdviceLogs" ThisKey="AdviceId" OtherKey="AdviceId" Type="BuyerAdviceLog" />
      <Association Name="AppImage_Advice" Member="AppImage" ThisKey="AppImageId" OtherKey="AppImageID" Type="AppImage" IsForeignKey="true" />
      <Association Name="Buyer_Advice" Member="Buyer" ThisKey="BuyerID" OtherKey="BuyerID" Type="Buyer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UnitMeasure" Member="UnitMeasures">
    <Type Name="UnitMeasure">
      <Column Name="UnitMeasureId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MagnitudeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Symbol" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UnitMeasureBaseId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Factor" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IsCustom" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="UnitMeasure_Product" Member="Products" ThisKey="UnitMeasureId" OtherKey="UnitMeasureId" Type="Product" />
      <Association Name="Magnitude_UnitMeasure" Member="Magnitude" ThisKey="MagnitudeId" OtherKey="MagnitudeId" Type="Magnitude" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AdviceButton" Member="AdviceButtons">
    <Type Name="AdviceButton">
      <Column Name="AdviceId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ButtonId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Advice_AdviceButton" Member="Advice" ThisKey="AdviceId" OtherKey="AdviceId" Type="Advice" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.App" Member="Apps">
    <Type Name="App">
      <Column Name="AppID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NotificationConnectionString" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="NotificationHubName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastVersion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateLastVersion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="App_Notification" Member="Notifications" ThisKey="AppID" OtherKey="AppID" Type="Notification" />
    </Type>
  </Table>
  <Table Name="dbo.AppImage" Member="AppImages">
    <Type Name="AppImage">
      <Column Name="AppImageID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ImageName" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="AppImage_Advice" Member="Advices" ThisKey="AppImageID" OtherKey="AppImageId" Type="Advice" />
      <Association Name="AppImage_Banner" Member="Banners" ThisKey="AppImageID" OtherKey="AppImageID" Type="Banner" />
      <Association Name="AppImage_Buyer" Member="Buyers" ThisKey="AppImageID" OtherKey="AppImageId" Type="Buyer" />
      <Association Name="AppImage_ContentSharing" Member="ContentSharings" ThisKey="AppImageID" OtherKey="AppImageID" Type="ContentSharing" />
      <Association Name="AppImage_Customer" Member="Customers" ThisKey="AppImageID" OtherKey="AppImageId" Type="Customer" />
      <Association Name="AppImage_Customer1" Member="Customers1" ThisKey="AppImageID" OtherKey="ThumbAppImageId" Type="Customer" />
      <Association Name="AppImage_CustomerLocation" Member="CustomerLocations" ThisKey="AppImageID" OtherKey="AppImageID" Type="CustomerLocation" />
      <Association Name="AppImage_CustomerVisit" Member="CustomerVisits" ThisKey="AppImageID" OtherKey="AppImageId" Type="CustomerVisit" />
      <Association Name="AppImage_EmployeeAdvice" Member="EmployeeAdvices" ThisKey="AppImageID" OtherKey="AppImageId" Type="EmployeeAdvice" />
      <Association Name="AppImage_MyOrderHistory" Member="MyOrderHistories" ThisKey="AppImageID" OtherKey="AppImageID" Type="MyOrderHistory" />
      <Association Name="AppImage_Product" Member="Products" ThisKey="AppImageID" OtherKey="AppImageID" Type="Product" />
      <Association Name="AppImage_Product1" Member="Products1" ThisKey="AppImageID" OtherKey="ThumbAppImageID" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Banner" Member="Banners">
    <Type Name="Banner">
      <Column Name="BannerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BannerActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AppImageID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="AppImage_Banner" Member="AppImage" ThisKey="AppImageID" OtherKey="AppImageID" Type="AppImage" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Buyer" Member="Buyers">
    <Type Name="Buyer">
      <Column Name="BuyerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DocumentNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SerialKey" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="IsBlocked" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Admin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AppImageId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Buyer_Advice" Member="Advices" ThisKey="BuyerID" OtherKey="BuyerID" Type="Advice" />
      <Association Name="Buyer_BuyerDevice" Member="BuyerDevices" ThisKey="BuyerID" OtherKey="BuyerID" Type="BuyerDevice" />
      <Association Name="Buyer_BuyerPromotion" Member="BuyerPromotions" ThisKey="BuyerID" OtherKey="BuyerID" Type="BuyerPromotion" />
      <Association Name="Buyer_BuyerSeller" Member="BuyerSellers" ThisKey="BuyerID" OtherKey="BuyerID" Type="BuyerSeller" />
      <Association Name="Buyer_ContentSharingLog" Member="ContentSharingLogs" ThisKey="BuyerID" OtherKey="BuyerID" Type="ContentSharingLog" />
      <Association Name="Buyer_MyOrder" Member="MyOrders" ThisKey="BuyerID" OtherKey="BuyerID" Type="MyOrder" />
      <Association Name="Buyer_Notification" Member="Notifications" ThisKey="BuyerID" OtherKey="BuyerID" Type="Notification" />
      <Association Name="AppImage_Buyer" Member="AppImage" ThisKey="AppImageId" OtherKey="AppImageID" Type="AppImage" IsForeignKey="true" />
      <Association Name="Customer_Buyer" Member="Customer" ThisKey="CustomerID" OtherKey="CustomerID" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BuyerAdviceLog" Member="BuyerAdviceLogs">
    <Type Name="BuyerAdviceLog">
      <Column Name="BuyerAdviceLogId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BuyerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdviceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ButtonId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Advice_BuyerAdviceLog" Member="Advice" ThisKey="AdviceId" OtherKey="AdviceId" Type="Advice" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BuyerDevice" Member="BuyerDevices">
    <Type Name="BuyerDevice">
      <Column Name="BuyerID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DeviceID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Buyer_BuyerDevice" Member="Buyer" ThisKey="BuyerID" OtherKey="BuyerID" Type="Buyer" IsForeignKey="true" />
      <Association Name="Device_BuyerDevice" Member="Device" ThisKey="DeviceID" OtherKey="DeviceID" Type="Device" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BuyerPromotion" Member="BuyerPromotions">
    <Type Name="BuyerPromotion">
      <Column Name="BuyerID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PromotionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="BuyerPromotion_PromotionReading" Member="PromotionReadings" ThisKey="BuyerID,PromotionID" OtherKey="BuyerID,PromotionID" Type="PromotionReading" />
      <Association Name="Buyer_BuyerPromotion" Member="Buyer" ThisKey="BuyerID" OtherKey="BuyerID" Type="Buyer" IsForeignKey="true" />
      <Association Name="Promotion_BuyerPromotion" Member="Promotion" ThisKey="PromotionID" OtherKey="PromotionID" Type="Promotion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BuyerSeller" Member="BuyerSellers">
    <Type Name="BuyerSeller">
      <Column Name="BuyerID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SellerID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OfficialSeller" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatorSeller" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Buyer_BuyerSeller" Member="Buyer" ThisKey="BuyerID" OtherKey="BuyerID" Type="Buyer" IsForeignKey="true" />
      <Association Name="Seller_BuyerSeller" Member="Seller" ThisKey="SellerID" OtherKey="SellerID" Type="Seller" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SupplierID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AppImageID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThumbAppImageID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Category_Category" Member="Categories" ThisKey="CategoryID" OtherKey="ParentID" Type="Category" />
      <Association Name="Category_CustomerTypeCategory" Member="CustomerTypeCategories" ThisKey="CategoryID" OtherKey="CategoryID" Type="CustomerTypeCategory" />
      <Association Name="Category_Product" Member="Products" ThisKey="CategoryID" OtherKey="CategoryID" Type="Product" />
      <Association Name="Category_Product1" Member="Products1" ThisKey="CategoryID" OtherKey="CategoryTempID" Type="Product" />
      <Association Name="Category_Category" Member="Category1" ThisKey="ParentID" OtherKey="CategoryID" Type="Category" IsForeignKey="true" />
      <Association Name="Supplier_Category" Member="Supplier" ThisKey="SupplierID" OtherKey="SupplierID" Type="Supplier" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.City" Member="Cities">
    <Type Name="City">
      <Column Name="CityID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CityName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="StateID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="City_CustomerLocation" Member="CustomerLocations" ThisKey="CityID" OtherKey="CityID" Type="CustomerLocation" />
    </Type>
  </Table>
  <Table Name="dbo.CodeLink" Member="CodeLinks">
    <Type Name="CodeLink">
      <Column Name="CodeLinkID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SellerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Used" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Seller_CodeLink" Member="Seller" ThisKey="SellerID" OtherKey="SellerID" Type="Seller" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ContentSharing" Member="ContentSharings">
    <Type Name="ContentSharing">
      <Column Name="ContentSharingId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Body" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="AppImageID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LinkURL" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="ContentSharing_ContentSharingLog" Member="ContentSharingLogs" ThisKey="ContentSharingId" OtherKey="ContentSharingId" Type="ContentSharingLog" />
      <Association Name="AppImage_ContentSharing" Member="AppImage" ThisKey="AppImageID" OtherKey="AppImageID" Type="AppImage" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ContentSharingLog" Member="ContentSharingLogs">
    <Type Name="ContentSharingLog">
      <Column Name="ContentSharingLogId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ContentSharingId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BuyerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ContactName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ContactEmail" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ContactPhone" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="UsingIOS" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Buyer_ContentSharingLog" Member="Buyer" ThisKey="BuyerID" OtherKey="BuyerID" Type="Buyer" IsForeignKey="true" />
      <Association Name="ContentSharing_ContentSharingLog" Member="ContentSharing" ThisKey="ContentSharingId" OtherKey="ContentSharingId" Type="ContentSharing" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Country" Member="Countries">
    <Type Name="Country">
      <Column Name="CountryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Gentilicio" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Country_Customer" Member="Customers" ThisKey="CountryID" OtherKey="CountryID" Type="Customer" />
    </Type>
  </Table>
  <Table Name="dbo.CreditPurchase" Member="CreditPurchases">
    <Type Name="CreditPurchase">
      <Column Name="CreditPurchaseId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PaymentMethod" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Customer_CreditPurchase" Member="Customer" ThisKey="CustomerID" OtherKey="CustomerID" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SegmentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Franchise" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BusinessName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CNPJ" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Longitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AppImageId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThumbAppImageId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Observation" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ContactName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ContactPhone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChiefName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ChiefPhone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustomerTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Credit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Vip" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CountryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Customer_Buyer" Member="Buyers" ThisKey="CustomerID" OtherKey="CustomerID" Type="Buyer" />
      <Association Name="Customer_CreditPurchase" Member="CreditPurchases" ThisKey="CustomerID" OtherKey="CustomerID" Type="CreditPurchase" />
      <Association Name="Customer_CustomerLocation" Member="CustomerLocations" ThisKey="CustomerID" OtherKey="CustomerID" Type="CustomerLocation" />
      <Association Name="Customer_CustomerReVisit" Member="CustomerReVisits" ThisKey="CustomerID" OtherKey="CustomerID" Type="CustomerReVisit" />
      <Association Name="Customer_CustomerVisit" Member="CustomerVisits" ThisKey="CustomerID" OtherKey="CustomerID" Type="CustomerVisit" />
      <Association Name="Customer_Bill" Member="Bills" ThisKey="CustomerID" OtherKey="CustomerID" Type="Bill" />
      <Association Name="AppImage_Customer" Member="AppImage" ThisKey="AppImageId" OtherKey="AppImageID" Type="AppImage" IsForeignKey="true" />
      <Association Name="AppImage_Customer1" Member="AppImage1" ThisKey="ThumbAppImageId" OtherKey="AppImageID" Type="AppImage" IsForeignKey="true" />
      <Association Name="Country_Customer" Member="Country" ThisKey="CountryID" OtherKey="CountryID" Type="Country" IsForeignKey="true" />
      <Association Name="CustomerType_Customer" Member="CustomerType" ThisKey="CustomerTypeID" OtherKey="CustomerTypeID" Type="CustomerType" IsForeignKey="true" />
      <Association Name="Segment_Customer" Member="Segment" ThisKey="SegmentID" OtherKey="SegmentID" Type="Segment" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CustomerLocation" Member="CustomerLocations">
    <Type Name="CustomerLocation">
      <Column Name="CustomerLocationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Number" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Complement" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Locality" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Reference" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="AppImageID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Temporary" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="CustomerLocation_MyOrderHistory" Member="MyOrderHistories" ThisKey="CustomerLocationID" OtherKey="CustomerLocationID" Type="MyOrderHistory" />
      <Association Name="City_CustomerLocation" Member="City" ThisKey="CityID" OtherKey="CityID" Type="City" IsForeignKey="true" />
      <Association Name="Customer_CustomerLocation" Member="Customer" ThisKey="CustomerID" OtherKey="CustomerID" Type="Customer" IsForeignKey="true" />
      <Association Name="AppImage_CustomerLocation" Member="AppImage" ThisKey="AppImageID" OtherKey="AppImageID" Type="AppImage" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CustomerResponse" Member="CustomerResponses">
    <Type Name="CustomerResponse">
      <Column Name="CustomerResponseID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Action" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="CustomerResponse_CustomerVisitProduct" Member="CustomerVisitProducts" ThisKey="CustomerResponseID" OtherKey="CustomerResponseID" Type="CustomerVisitProduct" />
    </Type>
  </Table>
  <Table Name="dbo.CustomerReVisit" Member="CustomerReVisits">
    <Type Name="CustomerReVisit">
      <Column Name="CustomerReVisitId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReVisitResultId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NextStep" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Customer_CustomerReVisit" Member="Customer" ThisKey="CustomerID" OtherKey="CustomerID" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CustomerType" Member="CustomerTypes">
    <Type Name="CustomerType">
      <Column Name="CustomerTypeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="CustomerType_Customer" Member="Customers" ThisKey="CustomerTypeID" OtherKey="CustomerTypeID" Type="Customer" />
      <Association Name="CustomerType_CustomerTypeCategory" Member="CustomerTypeCategories" ThisKey="CustomerTypeID" OtherKey="CustomerTypeID" Type="CustomerTypeCategory" />
      <Association Name="CustomerType_PriceList" Member="PriceLists" ThisKey="CustomerTypeID" OtherKey="CustomerTypeID" Type="PriceList" />
    </Type>
  </Table>
  <Table Name="dbo.CustomerTypeCategory" Member="CustomerTypeCategories">
    <Type Name="CustomerTypeCategory">
      <Column Name="CustomerTypeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Category_CustomerTypeCategory" Member="Category" ThisKey="CategoryID" OtherKey="CategoryID" Type="Category" IsForeignKey="true" />
      <Association Name="CustomerType_CustomerTypeCategory" Member="CustomerType" ThisKey="CustomerTypeID" OtherKey="CustomerTypeID" Type="CustomerType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CustomerVisit" Member="CustomerVisits">
    <Type Name="CustomerVisit">
      <Column Name="CustomerVisitID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SellerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Franchise" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SegmentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AppImageId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Observation" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="ContactName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ContactPhone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChiefName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ChiefPhone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="BusinessName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BusinessDocument" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ChiefDocument" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeliveryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VisitStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VisitEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="CustomerVisit_CustomerVisitProduct" Member="CustomerVisitProducts" ThisKey="CustomerVisitID" OtherKey="CustomerVisitID" Type="CustomerVisitProduct" />
      <Association Name="AppImage_CustomerVisit" Member="AppImage" ThisKey="AppImageId" OtherKey="AppImageID" Type="AppImage" IsForeignKey="true" />
      <Association Name="Customer_CustomerVisit" Member="Customer" ThisKey="CustomerID" OtherKey="CustomerID" Type="Customer" IsForeignKey="true" />
      <Association Name="Segment_CustomerVisit" Member="Segment" ThisKey="SegmentID" OtherKey="SegmentID" Type="Segment" IsForeignKey="true" />
      <Association Name="Seller_CustomerVisit" Member="Seller" ThisKey="SellerID" OtherKey="SellerID" Type="Seller" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CustomerVisitProduct" Member="CustomerVisitProducts">
    <Type Name="CustomerVisitProduct">
      <Column Name="CustomerVisitID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PriceListID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomerResponseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrderPeriodID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PeriodConsumptionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuantityConsumption" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CustomerResponse_CustomerVisitProduct" Member="CustomerResponse" ThisKey="CustomerResponseID" OtherKey="CustomerResponseID" Type="CustomerResponse" IsForeignKey="true" />
      <Association Name="CustomerVisit_CustomerVisitProduct" Member="CustomerVisit" ThisKey="CustomerVisitID" OtherKey="CustomerVisitID" Type="CustomerVisit" IsForeignKey="true" />
      <Association Name="PriceListDetail_CustomerVisitProduct" Member="PriceListDetail" ThisKey="PriceListID,ProductID" OtherKey="PriceListID,ProductID" Type="PriceListDetail" IsForeignKey="true" />
      <Association Name="Product_CustomerVisitProduct" Member="Product" ThisKey="ProductID" OtherKey="ProductID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Dealer" Member="Dealers">
    <Type Name="Dealer">
      <Column Name="DealerID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsBlocked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Dealer_MyOrderHistory" Member="MyOrderHistories" ThisKey="DealerID" OtherKey="DealerID" Type="MyOrderHistory" />
      <Association Name="Employee_Dealer" Member="Employee" ThisKey="DealerID" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Device" Member="Devices">
    <Type Name="Device">
      <Column Name="DeviceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DeviceToken" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="PushToken" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SimCardNumber" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DeviceOS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Device_BuyerDevice" Member="BuyerDevices" ThisKey="DeviceID" OtherKey="DeviceID" Type="BuyerDevice" />
      <Association Name="Device_EmployeeDevice" Member="EmployeeDevices" ThisKey="DeviceID" OtherKey="DeviceID" Type="EmployeeDevice" />
      <Association Name="Device_SellerDevice" Member="SellerDevices" ThisKey="DeviceID" OtherKey="DeviceID" Type="SellerDevice" />
    </Type>
  </Table>
  <Table Name="dbo.EmailNotification" Member="EmailNotifications">
    <Type Name="EmailNotification">
      <Column Name="EmailNotificationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmailFrom" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EmailTo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="BodyText" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="BodyHtml" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DateToSend" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Send" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SupplierID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Gender" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="SerialKey" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Employee_Dealer" Member="Dealer" ThisKey="EmployeeID" OtherKey="DealerID" Type="Dealer" Cardinality="One" />
      <Association Name="Employee_EmployeeAdvice" Member="EmployeeAdvices" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="EmployeeAdvice" />
      <Association Name="Employee_EmployeeDevice" Member="EmployeeDevices" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="EmployeeDevice" />
      <Association Name="Employee_MyOrderHistory" Member="MyOrderHistories" ThisKey="EmployeeID" OtherKey="InteractorEmployeeId" Type="MyOrderHistory" />
      <Association Name="Employee_Seller" Member="Seller" ThisKey="EmployeeID" OtherKey="SellerID" Type="Seller" Cardinality="One" />
      <Association Name="Employee_Version" Member="Versions" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Version" />
      <Association Name="Supplier_Employee" Member="Supplier" ThisKey="SupplierID" OtherKey="SupplierID" Type="Supplier" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EmployeeAdvice" Member="EmployeeAdvices">
    <Type Name="EmployeeAdvice">
      <Column Name="EmployeeAdviceId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IsPublic" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeeType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Call" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Body" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="AppImageId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PictureName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Argument" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Highlight" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="EmployeeAdvice_EmployeeAdviceButton" Member="EmployeeAdviceButtons" ThisKey="EmployeeAdviceId" OtherKey="EmployeeAdviceId" Type="EmployeeAdviceButton" />
      <Association Name="EmployeeAdvice_EmployeeAdviceLog" Member="EmployeeAdviceLogs" ThisKey="EmployeeAdviceId" OtherKey="EmployeeAdviceId" Type="EmployeeAdviceLog" />
      <Association Name="AppImage_EmployeeAdvice" Member="AppImage" ThisKey="AppImageId" OtherKey="AppImageID" Type="AppImage" IsForeignKey="true" />
      <Association Name="Employee_EmployeeAdvice" Member="Employee" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EmployeeAdviceButton" Member="EmployeeAdviceButtons">
    <Type Name="EmployeeAdviceButton">
      <Column Name="EmployeeAdviceId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ButtonId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="EmployeeAdvice_EmployeeAdviceButton" Member="EmployeeAdvice" ThisKey="EmployeeAdviceId" OtherKey="EmployeeAdviceId" Type="EmployeeAdvice" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EmployeeAdviceLog" Member="EmployeeAdviceLogs">
    <Type Name="EmployeeAdviceLog">
      <Column Name="EmployeeAdviceLogId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeAdviceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ButtonId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="EmployeeAdvice_EmployeeAdviceLog" Member="EmployeeAdvice" ThisKey="EmployeeAdviceId" OtherKey="EmployeeAdviceId" Type="EmployeeAdvice" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EmployeeDevice" Member="EmployeeDevices">
    <Type Name="EmployeeDevice">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DeviceID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Device_EmployeeDevice" Member="Device" ThisKey="DeviceID" OtherKey="DeviceID" Type="Device" IsForeignKey="true" />
      <Association Name="Employee_EmployeeDevice" Member="Employee" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Magnitude" Member="Magnitudes">
    <Type Name="Magnitude">
      <Column Name="MagnitudeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Magnitude_UnitMeasure" Member="UnitMeasures" ThisKey="MagnitudeId" OtherKey="MagnitudeId" Type="UnitMeasure" />
    </Type>
  </Table>
  <Table Name="dbo.Meter" Member="Meters">
    <Type Name="Meter">
      <Column Name="MeterId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Enable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Meter_MeterCategory" Member="MeterCategories" ThisKey="MeterId" OtherKey="MeterId" Type="MeterCategory" />
    </Type>
  </Table>
  <Table Name="dbo.MeterCategory" Member="MeterCategories">
    <Type Name="MeterCategory">
      <Column Name="MeterCategoryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MeterId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ManConsum" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="WomanConsum" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ChildConsum" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="UnitMeasureId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Enable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="MeterCategory_MeterCategoryProduct" Member="MeterCategoryProducts" ThisKey="MeterCategoryId" OtherKey="MeterCategoryId" Type="MeterCategoryProduct" />
      <Association Name="Meter_MeterCategory" Member="Meter" ThisKey="MeterId" OtherKey="MeterId" Type="Meter" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MeterCategoryProduct" Member="MeterCategoryProducts">
    <Type Name="MeterCategoryProduct">
      <Column Name="MeterCategoryId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Enable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="MeterCategory_MeterCategoryProduct" Member="MeterCategory" ThisKey="MeterCategoryId" OtherKey="MeterCategoryId" Type="MeterCategory" IsForeignKey="true" />
      <Association Name="Product_MeterCategoryProduct" Member="Product" ThisKey="ProductID" OtherKey="ProductID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MyOrder" Member="MyOrders">
    <Type Name="MyOrder">
      <Column Name="MyOrderID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BuyerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SupplierID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PromotionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MyOrderType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReceiptCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Product" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RepeatOrder" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Sort" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrintInvoice" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="MyOrder_MyOrderHistory" Member="MyOrderHistories" ThisKey="MyOrderID" OtherKey="MyOrderID" Type="MyOrderHistory" />
      <Association Name="MyOrder_MyOrderProduct" Member="MyOrderProducts" ThisKey="MyOrderID" OtherKey="MyOrderID" Type="MyOrderProduct" />
      <Association Name="Buyer_MyOrder" Member="Buyer" ThisKey="BuyerID" OtherKey="BuyerID" Type="Buyer" IsForeignKey="true" />
      <Association Name="Promotion_MyOrder" Member="Promotion" ThisKey="PromotionID" OtherKey="PromotionID" Type="Promotion" IsForeignKey="true" />
      <Association Name="Supplier_MyOrder" Member="Supplier" ThisKey="SupplierID" OtherKey="SupplierID" Type="Supplier" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MyOrderHistory" Member="MyOrderHistories">
    <Type Name="MyOrderHistory">
      <Column Name="MyOrderHistoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MyOrderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InteractionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NotificationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SellerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DealerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InteractorEmployeeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomerLocationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cost" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PayMode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PaymentMethod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChangeOf" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="InvoiceNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="InvoiceDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Observation" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DeliveryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ShippingCost" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="TrackPointID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AppImageID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Receiver" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CancelDescription" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Association Name="AppImage_MyOrderHistory" Member="AppImage" ThisKey="AppImageID" OtherKey="AppImageID" Type="AppImage" IsForeignKey="true" />
      <Association Name="CustomerLocation_MyOrderHistory" Member="CustomerLocation" ThisKey="CustomerLocationID" OtherKey="CustomerLocationID" Type="CustomerLocation" IsForeignKey="true" />
      <Association Name="Dealer_MyOrderHistory" Member="Dealer" ThisKey="DealerID" OtherKey="DealerID" Type="Dealer" IsForeignKey="true" />
      <Association Name="Employee_MyOrderHistory" Member="Employee" ThisKey="InteractorEmployeeId" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
      <Association Name="MyOrder_MyOrderHistory" Member="MyOrder" ThisKey="MyOrderID" OtherKey="MyOrderID" Type="MyOrder" IsForeignKey="true" />
      <Association Name="Notification_MyOrderHistory" Member="Notification" ThisKey="NotificationID" OtherKey="NotificationID" Type="Notification" IsForeignKey="true" />
      <Association Name="Seller_MyOrderHistory" Member="Seller" ThisKey="SellerID" OtherKey="SellerID" Type="Seller" IsForeignKey="true" />
      <Association Name="TrackPoint_MyOrderHistory" Member="TrackPoint" ThisKey="TrackPointID" OtherKey="TrackPointID" Type="TrackPoint" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MyOrderProduct" Member="MyOrderProducts">
    <Type Name="MyOrderProduct">
      <Column Name="MyOrderID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PriceListID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cost" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SalePrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="InOffer" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Discount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuantityInitial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiscountInitial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsAdded" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="MyOrder_MyOrderProduct" Member="MyOrder" ThisKey="MyOrderID" OtherKey="MyOrderID" Type="MyOrder" IsForeignKey="true" />
      <Association Name="PriceListDetail_MyOrderProduct" Member="PriceListDetail" ThisKey="PriceListID,ProductID" OtherKey="PriceListID,ProductID" Type="PriceListDetail" IsForeignKey="true" />
      <Association Name="Product_MyOrderProduct" Member="Product" ThisKey="ProductID" OtherKey="ProductID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Notification" Member="Notifications">
    <Type Name="Notification">
      <Column Name="NotificationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AppID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BuyerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeviceOS" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Channel" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ContentTitle" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ContentText" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="LargeIcon" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SmallIcon" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Activity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Argument" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DateToSend" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Menu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Send" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsRead" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Notification_MyOrderHistory" Member="MyOrderHistories" ThisKey="NotificationID" OtherKey="NotificationID" Type="MyOrderHistory" />
      <Association Name="App_Notification" Member="App" ThisKey="AppID" OtherKey="AppID" Type="App" IsForeignKey="true" />
      <Association Name="Buyer_Notification" Member="Buyer" ThisKey="BuyerID" OtherKey="BuyerID" Type="Buyer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PriceList" Member="PriceLists">
    <Type Name="PriceList">
      <Column Name="PriceListID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="PriceList_PriceListDetail" Member="PriceListDetails" ThisKey="PriceListID" OtherKey="PriceListID" Type="PriceListDetail" />
      <Association Name="CustomerType_PriceList" Member="CustomerType" ThisKey="CustomerTypeID" OtherKey="CustomerTypeID" Type="CustomerType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PriceListDetail" Member="PriceListDetails">
    <Type Name="PriceListDetail">
      <Column Name="PriceListID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Margin" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SalePrice" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="MarginDiscount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DiscountPrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="OfferPrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="MinimumQuantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaximumDiscount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="PriceListDetail_CustomerVisitProduct" Member="CustomerVisitProducts" ThisKey="PriceListID,ProductID" OtherKey="PriceListID,ProductID" Type="CustomerVisitProduct" />
      <Association Name="PriceListDetail_MyOrderProduct" Member="MyOrderProducts" ThisKey="PriceListID,ProductID" OtherKey="PriceListID,ProductID" Type="MyOrderProduct" />
      <Association Name="PriceList_PriceListDetail" Member="PriceList" ThisKey="PriceListID" OtherKey="PriceListID" Type="PriceList" IsForeignKey="true" />
      <Association Name="Product_PriceListDetail" Member="Product" ThisKey="ProductID" OtherKey="ProductID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PrintInvoice" Member="PrintInvoices">
    <Type Name="PrintInvoice">
      <Column Name="PrintInvoiceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MyOrderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="InvoiceDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Printed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ResultMessage" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AppImageID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThumbAppImageID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CostPrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Cost" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="CostShow" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Discount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryTempID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExternalID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Manufacturer" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Udm" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UnitMeasureId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IvaType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Product_CustomerVisitProduct" Member="CustomerVisitProducts" ThisKey="ProductID" OtherKey="ProductID" Type="CustomerVisitProduct" />
      <Association Name="Product_MeterCategoryProduct" Member="MeterCategoryProducts" ThisKey="ProductID" OtherKey="ProductID" Type="MeterCategoryProduct" />
      <Association Name="Product_MyOrderProduct" Member="MyOrderProducts" ThisKey="ProductID" OtherKey="ProductID" Type="MyOrderProduct" />
      <Association Name="Product_PriceListDetail" Member="PriceListDetails" ThisKey="ProductID" OtherKey="ProductID" Type="PriceListDetail" />
      <Association Name="AppImage_Product" Member="AppImage" ThisKey="AppImageID" OtherKey="AppImageID" Type="AppImage" IsForeignKey="true" />
      <Association Name="AppImage_Product1" Member="AppImage1" ThisKey="ThumbAppImageID" OtherKey="AppImageID" Type="AppImage" IsForeignKey="true" />
      <Association Name="Category_Product" Member="Category" ThisKey="CategoryID" OtherKey="CategoryID" Type="Category" IsForeignKey="true" />
      <Association Name="Category_Product1" Member="Category1" ThisKey="CategoryTempID" OtherKey="CategoryID" Type="Category" IsForeignKey="true" />
      <Association Name="UnitMeasure_Product" Member="UnitMeasure" ThisKey="UnitMeasureId" OtherKey="UnitMeasureId" Type="UnitMeasure" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Promotion" Member="Promotions">
    <Type Name="Promotion">
      <Column Name="PromotionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SellerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExpirationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Product" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Cost" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImageURL" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Promotion_BuyerPromotion" Member="BuyerPromotions" ThisKey="PromotionID" OtherKey="PromotionID" Type="BuyerPromotion" />
      <Association Name="Promotion_MyOrder" Member="MyOrders" ThisKey="PromotionID" OtherKey="PromotionID" Type="MyOrder" />
      <Association Name="Seller_Promotion" Member="Seller" ThisKey="SellerID" OtherKey="SellerID" Type="Seller" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PromotionReading" Member="PromotionReadings">
    <Type Name="PromotionReading">
      <Column Name="PromotionReadingID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BuyerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PromotionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="BuyerPromotion_PromotionReading" Member="BuyerPromotion" ThisKey="BuyerID,PromotionID" OtherKey="BuyerID,PromotionID" Type="BuyerPromotion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Segment" Member="Segments">
    <Type Name="Segment">
      <Column Name="SegmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Segment_Customer" Member="Customers" ThisKey="SegmentID" OtherKey="SegmentID" Type="Customer" />
      <Association Name="Segment_CustomerVisit" Member="CustomerVisits" ThisKey="SegmentID" OtherKey="SegmentID" Type="CustomerVisit" />
    </Type>
  </Table>
  <Table Name="dbo.Seller" Member="Sellers">
    <Type Name="Seller">
      <Column Name="SellerID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsBlocked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Seller_BuyerSeller" Member="BuyerSellers" ThisKey="SellerID" OtherKey="SellerID" Type="BuyerSeller" />
      <Association Name="Seller_CodeLink" Member="CodeLinks" ThisKey="SellerID" OtherKey="SellerID" Type="CodeLink" />
      <Association Name="Seller_CustomerVisit" Member="CustomerVisits" ThisKey="SellerID" OtherKey="SellerID" Type="CustomerVisit" />
      <Association Name="Seller_MyOrderHistory" Member="MyOrderHistories" ThisKey="SellerID" OtherKey="SellerID" Type="MyOrderHistory" />
      <Association Name="Seller_Promotion" Member="Promotions" ThisKey="SellerID" OtherKey="SellerID" Type="Promotion" />
      <Association Name="Seller_SellerDevice" Member="SellerDevices" ThisKey="SellerID" OtherKey="SellerID" Type="SellerDevice" />
      <Association Name="Seller_SellerTrackPoint" Member="SellerTrackPoints" ThisKey="SellerID" OtherKey="SellerID" Type="SellerTrackPoint" />
      <Association Name="Seller_SellerWorkingDay" Member="SellerWorkingDays" ThisKey="SellerID" OtherKey="SellerID" Type="SellerWorkingDay" />
      <Association Name="Seller_UserRole" Member="UserRoles" ThisKey="SellerID" OtherKey="SellerId" Type="UserRole" />
      <Association Name="Employee_Seller" Member="Employee" ThisKey="SellerID" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SellerDevice" Member="SellerDevices">
    <Type Name="SellerDevice">
      <Column Name="SellerID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DeviceID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Device_SellerDevice" Member="Device" ThisKey="DeviceID" OtherKey="DeviceID" Type="Device" IsForeignKey="true" />
      <Association Name="Seller_SellerDevice" Member="Seller" ThisKey="SellerID" OtherKey="SellerID" Type="Seller" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SellerTrackPoint" Member="SellerTrackPoints">
    <Type Name="SellerTrackPoint">
      <Column Name="SellerID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TrackPointID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Seller_SellerTrackPoint" Member="Seller" ThisKey="SellerID" OtherKey="SellerID" Type="Seller" IsForeignKey="true" />
      <Association Name="TrackPoint_SellerTrackPoint" Member="TrackPoint" ThisKey="TrackPointID" OtherKey="TrackPointID" Type="TrackPoint" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SellerWorkingDay" Member="SellerWorkingDays">
    <Type Name="SellerWorkingDay">
      <Column Name="SellerWorkingDayID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SellerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TrackPointID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WorkingDayDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Seller_SellerWorkingDay" Member="Seller" ThisKey="SellerID" OtherKey="SellerID" Type="Seller" IsForeignKey="true" />
      <Association Name="TrackPoint_SellerWorkingDay" Member="TrackPoint" ThisKey="TrackPointID" OtherKey="TrackPointID" Type="TrackPoint" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ShippingCostRule" Member="ShippingCostRules">
    <Type Name="ShippingCostRule">
      <Column Name="ShippingCostRuleId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Value" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Supplier" Member="Suppliers">
    <Type Name="Supplier">
      <Column Name="SupplierID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CNPJ" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Longitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IsPay" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SerialKey" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Supplier_Category" Member="Categories" ThisKey="SupplierID" OtherKey="SupplierID" Type="Category" />
      <Association Name="Supplier_Employee" Member="Employees" ThisKey="SupplierID" OtherKey="SupplierID" Type="Employee" />
      <Association Name="Supplier_MyOrder" Member="MyOrders" ThisKey="SupplierID" OtherKey="SupplierID" Type="MyOrder" />
    </Type>
  </Table>
  <Table Name="dbo.TrackPoint" Member="TrackPoints">
    <Type Name="TrackPoint">
      <Column Name="TrackPointID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TrackPointTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateGPS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TrackPoint_MyOrderHistory" Member="MyOrderHistories" ThisKey="TrackPointID" OtherKey="TrackPointID" Type="MyOrderHistory" />
      <Association Name="TrackPoint_SellerTrackPoint" Member="SellerTrackPoints" ThisKey="TrackPointID" OtherKey="TrackPointID" Type="SellerTrackPoint" />
      <Association Name="TrackPoint_SellerWorkingDay" Member="SellerWorkingDays" ThisKey="TrackPointID" OtherKey="TrackPointID" Type="SellerWorkingDay" />
      <Association Name="TrackPointType_TrackPoint" Member="TrackPointType" ThisKey="TrackPointTypeID" OtherKey="TrackPointTypeID" Type="TrackPointType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TrackPointType" Member="TrackPointTypes">
    <Type Name="TrackPointType">
      <Column Name="TrackPointTypeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TrackPointType_TrackPoint" Member="TrackPoints" ThisKey="TrackPointTypeID" OtherKey="TrackPointTypeID" Type="TrackPoint" />
    </Type>
  </Table>
  <Table Name="dbo.Version" Member="Versions">
    <Type Name="Version">
      <Column Name="VersionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Version" Member="Version1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Employee_Version" Member="Employee" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SupplierRecommendation" Member="SupplierRecommendations">
    <Type Name="SupplierRecommendation">
      <Column Name="SupplierRecommendationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Identification" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="SerialKey" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SegmentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Role_UserRole" Member="UserRoles" ThisKey="RoleID" OtherKey="RoleId" Type="UserRole" />
    </Type>
  </Table>
  <Table Name="dbo.UserRole" Member="UserRoles">
    <Type Name="UserRole">
      <Column Name="SellerId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Role_UserRole" Member="Role" ThisKey="RoleId" OtherKey="RoleID" Type="Role" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Seller_UserRole" Member="Seller" ThisKey="SellerId" OtherKey="SellerID" Type="Seller" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bill" Member="Bills">
    <Type Name="Bill">
      <Column Name="BillID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="Value" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Obs" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Paid" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Customer_Bill" Member="Customer" ThisKey="CustomerID" OtherKey="CustomerID" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.spLastSellerLocation" Method="spLastSellerLocation">
    <Parameter Name="Fecha" Parameter="fecha" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="spLastSellerLocationResult">
      <Column Name="SellerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(101)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DateGPS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spListTodayTravelPoint" Method="spListTodayTravelPoint">
    <Parameter Name="SellerID" Parameter="sellerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Fecha" Parameter="fecha" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="spListTodayTravelPointResult">
      <Column Name="SellerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DateGPS" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spLastSellerAlive" Method="spLastSellerAlive">
    <Parameter Name="Fecha" Parameter="fecha" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="spLastSellerAliveResult">
      <Column Name="SellerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(101)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DateGPS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spAdminOrderList" Method="spAdminOrderList">
    <Parameter Name="SupplierID" Parameter="supplierID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DealerID" Parameter="dealerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="statusList" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="orderTypeList" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="DateIni" Parameter="dateIni" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="DateFin" Parameter="dateFin" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Page" Parameter="page" Type="System.Int32" DbType="Int" />
    <ElementType Name="spAdminOrderListResult">
      <Column Name="Address" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Number" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeliveryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MyOrderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReceiptCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MyOrderType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SellerFirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SellerLastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spDealerOrderList" Method="spDealerOrderList">
    <Parameter Name="DealerID" Parameter="dealerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="statusList" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="DateIni" Parameter="dateIni" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="DateFin" Parameter="dateFin" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Page" Parameter="page" Type="System.Int32" DbType="Int" />
    <ElementType Name="spDealerOrderListResult">
      <Column Name="Address" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Number" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeliveryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MyOrderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReceiptCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MyOrderType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SellerFirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SellerLastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spSellerOrderList" Method="spSellerOrderList">
    <Parameter Name="SupplierID" Parameter="supplierID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SellerID" Parameter="sellerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="statusList" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="OrderTypeList" Parameter="orderTypeList" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="DeliveryDate" Parameter="deliveryDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Page" Parameter="page" Type="System.Int32" DbType="Int" />
    <ElementType Name="spSellerOrderListResult">
      <Column Name="Address" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Number" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeliveryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MyOrderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReceiptCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MyOrderType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SellerFirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SellerLastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DealerFirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DealerLastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>