//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorRes() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ErrorRes", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a General Error.
        /// </summary>
        internal static string E000 {
            get {
                return ResourceManager.GetString("E000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Usuario ou senha invalido.
        /// </summary>
        internal static string E001 {
            get {
                return ResourceManager.GetString("E001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Equipamento não localizado.
        /// </summary>
        internal static string E002 {
            get {
                return ResourceManager.GetString("E002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a O equipamento que você está usando no esta vinculado a su cuenta.
        /// </summary>
        internal static string E003 {
            get {
                return ResourceManager.GetString("E003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Funcionário inativo.
        /// </summary>
        internal static string E004 {
            get {
                return ResourceManager.GetString("E004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Funcionário bloqueado.
        /// </summary>
        internal static string E005 {
            get {
                return ResourceManager.GetString("E005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Funcionário não tem permissão para acessar este aplicativo.
        /// </summary>
        internal static string E006 {
            get {
                return ResourceManager.GetString("E006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Funcionário não está habilitado.
        /// </summary>
        internal static string E007 {
            get {
                return ResourceManager.GetString("E007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Funcionário ya registrado.
        /// </summary>
        internal static string E008 {
            get {
                return ResourceManager.GetString("E008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Código de vinculação invalido.
        /// </summary>
        internal static string E009 {
            get {
                return ResourceManager.GetString("E009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Provedor ja esta relacionado.
        /// </summary>
        internal static string E010 {
            get {
                return ResourceManager.GetString("E010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a já tem uma chamada aberta para este fornecedor.
        /// </summary>
        internal static string E011 {
            get {
                return ResourceManager.GetString("E011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a já tem uma ordem de promoção aberta para este fornecedor.
        /// </summary>
        internal static string E012 {
            get {
                return ResourceManager.GetString("E012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a já tem uma ordem aberta para este fornecedor.
        /// </summary>
        internal static string E013 {
            get {
                return ResourceManager.GetString("E013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Voce não tem cadastro uma ultima ordem!.
        /// </summary>
        internal static string E014 {
            get {
                return ResourceManager.GetString("E014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a No existe el pedido indicado.
        /// </summary>
        internal static string E015 {
            get {
                return ResourceManager.GetString("E015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Já está registrada uma pessoa com e mesmo E-mail.
        /// </summary>
        internal static string E016 {
            get {
                return ResourceManager.GetString("E016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Senha atual inválida!.
        /// </summary>
        internal static string E017 {
            get {
                return ResourceManager.GetString("E017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a E-mail não registrado.
        /// </summary>
        internal static string E018 {
            get {
                return ResourceManager.GetString("E018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Funcionario não localizado.
        /// </summary>
        internal static string E019 {
            get {
                return ResourceManager.GetString("E019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Empresa já existente, entre em contato com o administrador para se registrar.
        /// </summary>
        internal static string E020 {
            get {
                return ResourceManager.GetString("E020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Esta empresa ya esta registrada como cliente.
        /// </summary>
        internal static string E021 {
            get {
                return ResourceManager.GetString("E021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Ya ha iniciado Jornada el dia de hoy.
        /// </summary>
        internal static string E022 {
            get {
                return ResourceManager.GetString("E022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Ya ha finalizado Jornada el dia de hoy.
        /// </summary>
        internal static string E023 {
            get {
                return ResourceManager.GetString("E023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Cliente no encontrado.
        /// </summary>
        internal static string E024 {
            get {
                return ResourceManager.GetString("E024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a El pedido ya esta en proceso. No puede ser cancelado. Comuniquese con el equipo Japo..
        /// </summary>
        internal static string E025 {
            get {
                return ResourceManager.GetString("E025", resourceCulture);
            }
        }
    }
}
