//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NotificationPush {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationPush() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.NotificationPush", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido enviado#Seu pedido foi registrado com êxito.
        /// </summary>
        internal static string N001 {
            get {
                return ResourceManager.GetString("N001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra de Crédito.#Recibimos su solicitud de crédito, por favor, aguarde el contacto de nuestro equipo Japo.
        /// </summary>
        internal static string N002 {
            get {
                return ResourceManager.GetString("N002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Pedido.!#Un cliente ha efectuado un nuevo pedido.
        /// </summary>
        internal static string N003 {
            get {
                return ResourceManager.GetString("N003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra de Crédito.#Un cliente ha efectuado una compra de crédito.
        /// </summary>
        internal static string N004 {
            get {
                return ResourceManager.GetString("N004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparando Pedido#Su pedido esta siendo preparado para ser enviado.
        /// </summary>
        internal static string N005 {
            get {
                return ResourceManager.GetString("N005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido en Camino#Su pedido ya esta en camino.
        /// </summary>
        internal static string N006 {
            get {
                return ResourceManager.GetString("N006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido Recibido#Su pedido fue entregado satisfactoriamente. Gracias por su confianza..
        /// </summary>
        internal static string N007 {
            get {
                return ResourceManager.GetString("N007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido con Inconveniente#Su pedido tuvo un inconveniente al intentar realizar la entrega: {StatusPedido}. Por favor entre en contacto.
        /// </summary>
        internal static string N008 {
            get {
                return ResourceManager.GetString("N008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido Cancelado#Su pedido fue cancelado.
        /// </summary>
        internal static string N009 {
            get {
                return ResourceManager.GetString("N009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status de Crédito#Su crédito fue aplicado satisfactoriamente. Su saldo es de: {SaldoCredito}.
        /// </summary>
        internal static string N010 {
            get {
                return ResourceManager.GetString("N010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status de Crédito#Su crédito no fue aprobado, por favor, entre en contacto con nuestro Equipo Japo.
        /// </summary>
        internal static string N011 {
            get {
                return ResourceManager.GetString("N011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status de Crédito#Ha realizado una compra utilizando su Crédito Japo. Saldo actual: {SaldoCredito}.
        /// </summary>
        internal static string N012 {
            get {
                return ResourceManager.GetString("N012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promoción#Tenemos una promoción para usted, por favor, ingrese a la App Japo.
        /// </summary>
        internal static string N013 {
            get {
                return ResourceManager.GetString("N013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido Asignado#Se le ha sido asignado un pedido para realizar la entrega.
        /// </summary>
        internal static string N014 {
            get {
                return ResourceManager.GetString("N014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {TypeTitle} de Jornada#{SellerName} ha {Type} la jornada..
        /// </summary>
        internal static string N015 {
            get {
                return ResourceManager.GetString("N015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido En Proceso#El Pedido para su cliente: {CustomerName} generado el: {DateOrder} fue Asignado al repartidor: {DealerName}..
        /// </summary>
        internal static string N016 {
            get {
                return ResourceManager.GetString("N016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Oportunidad#{DealerName} ha registrado para usted una nueva oportunidad. Cliente Prospecto: {CustomerName} .
        /// </summary>
        internal static string N017 {
            get {
                return ResourceManager.GetString("N017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido En Camino#El pedido para su cliente {CustomerName} generado el: {DateOrder} ya esta en camino..
        /// </summary>
        internal static string N018 {
            get {
                return ResourceManager.GetString("N018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido con Inconveniente#El Pedido para su cliente: {CustomerName} generado el: {DateOrder} tuvo un inconveniente al intentar realizar la entrega: {StatusPedido}.
        /// </summary>
        internal static string N019 {
            get {
                return ResourceManager.GetString("N019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido Entregado#El Pedido para su cliente: {CustomerName} generado el: {DateOrder} fue entregado satisfactoriamente..
        /// </summary>
        internal static string N020 {
            get {
                return ResourceManager.GetString("N020", resourceCulture);
            }
        }
    }
}
