//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewT.Crediario.Domain.Main.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViewT.Crediario.Domain.Main.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppImageId inválido.
        /// </summary>
        internal static string AppImageIdInvalid {
            get {
                return ResourceManager.GetString("AppImageIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppImageId não informado.
        /// </summary>
        internal static string AppImageIdRequired {
            get {
                return ResourceManager.GetString("AppImageIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem não encontrada.
        /// </summary>
        internal static string AppImageNotFound {
            get {
                return ResourceManager.GetString("AppImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do condomínio tem menos de 6 caracteres.
        /// </summary>
        internal static string CondoAddNewCondoNameMoreThan6 {
            get {
                return ResourceManager.GetString("CondoAddNewCondoNameMoreThan6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do condomínio não informado.
        /// </summary>
        internal static string CondoAddNewCondoNameRequired {
            get {
                return ResourceManager.GetString("CondoAddNewCondoNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa não possui condomínio vinculado.
        /// </summary>
        internal static string CondoGenerateCodePersonHasNoLinkedCondo {
            get {
                return ResourceManager.GetString("CondoGenerateCodePersonHasNoLinkedCondo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa não possui status de Administrador.
        /// </summary>
        internal static string CondoGenerateCodePersonIsNotAdmin {
            get {
                return ResourceManager.GetString("CondoGenerateCodePersonIsNotAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email não é válido.
        /// </summary>
        internal static string EmailProper {
            get {
                return ResourceManager.GetString("EmailProper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email não informado.
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem não encontrada.
        /// </summary>
        internal static string ImageNotFound {
            get {
                return ResourceManager.GetString("ImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisição inválida.
        /// </summary>
        internal static string InvalidCommandRequested {
            get {
                return ResourceManager.GetString("InvalidCommandRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de vinculação não encontrado.
        /// </summary>
        internal static string PersonLinkCondoCodeCondoCodeNotFound {
            get {
                return ResourceManager.GetString("PersonLinkCondoCodeCondoCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de vinculação não informado.
        /// </summary>
        internal static string PersonLinkCondoCodeCondoCodeRequired {
            get {
                return ResourceManager.GetString("PersonLinkCondoCodeCondoCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa já possui condomínio vinculado.
        /// </summary>
        internal static string PersonLinkCondoCodePersonHasAlreadyLinkedCondo {
            get {
                return ResourceManager.GetString("PersonLinkCondoCodePersonHasAlreadyLinkedCondo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento não informado.
        /// </summary>
        internal static string PersonUpdateProfileDocumentNumberRequired {
            get {
                return ResourceManager.GetString("PersonUpdateProfileDocumentNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome não informado.
        /// </summary>
        internal static string PersonUpdateProfileNameRequired {
            get {
                return ResourceManager.GetString("PersonUpdateProfileNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone não informado.
        /// </summary>
        internal static string PersonUpdateProfilePhoneNumberRequired {
            get {
                return ResourceManager.GetString("PersonUpdateProfilePhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id do veículo não informado.
        /// </summary>
        internal static string PersonVehicleIdRequired {
            get {
                return ResourceManager.GetString("PersonVehicleIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placa do veículo não informada.
        /// </summary>
        internal static string PersonVehicleLicensePlateRequired {
            get {
                return ResourceManager.GetString("PersonVehicleLicensePlateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo do veículo não informado.
        /// </summary>
        internal static string PersonVehicleModelRequired {
            get {
                return ResourceManager.GetString("PersonVehicleModelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O push token é obrigatório.
        /// </summary>
        internal static string PushTokenRequired {
            get {
                return ResourceManager.GetString("PushTokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SerialKey não informado.
        /// </summary>
        internal static string SerialKeyRequired {
            get {
                return ResourceManager.GetString("SerialKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem não informada.
        /// </summary>
        internal static string UserAppImageBase64StringImageRequired {
            get {
                return ResourceManager.GetString("UserAppImageBase64StringImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem não encontrada.
        /// </summary>
        internal static string UserAppImageNotFound {
            get {
                return ResourceManager.GetString("UserAppImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário ou senha não conferem. Login falhou..
        /// </summary>
        internal static string UserAuthenticateLoginFailed {
            get {
                return ResourceManager.GetString("UserAuthenticateLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha não informada.
        /// </summary>
        internal static string UserAuthenticatePasswordRequired {
            get {
                return ResourceManager.GetString("UserAuthenticatePasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário está desabilitado.
        /// </summary>
        internal static string UserAuthenticateUserIsInactive {
            get {
                return ResourceManager.GetString("UserAuthenticateUserIsInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não informado.
        /// </summary>
        internal static string UserAuthenticateUserRequired {
            get {
                return ResourceManager.GetString("UserAuthenticateUserRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device não está vinculado a usuário.
        /// </summary>
        internal static string UserChangePasswordDeviceDoesNotBelongToUser {
            get {
                return ResourceManager.GetString("UserChangePasswordDeviceDoesNotBelongToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device não encontrado.
        /// </summary>
        internal static string UserChangePasswordDeviceNotFound {
            get {
                return ResourceManager.GetString("UserChangePasswordDeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification não informado.
        /// </summary>
        internal static string UserChangePasswordIdentificationRequired {
            get {
                return ResourceManager.GetString("UserChangePasswordIdentificationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email não é válido.
        /// </summary>
        internal static string UserForgotPasswordEmailProper {
            get {
                return ResourceManager.GetString("UserForgotPasswordEmailProper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email não informado.
        /// </summary>
        internal static string UserForgotPasswordEmailRequired {
            get {
                return ResourceManager.GetString("UserForgotPasswordEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email já cadastrado.
        /// </summary>
        internal static string UserRegisterEmailAlreadyTaken {
            get {
                return ResourceManager.GetString("UserRegisterEmailAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha não é válida.
        /// </summary>
        internal static string UserRegisterPasswordProper {
            get {
                return ResourceManager.GetString("UserRegisterPasswordProper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha não informada.
        /// </summary>
        internal static string UserRegisterPasswordRequired {
            get {
                return ResourceManager.GetString("UserRegisterPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veículo não encontrado.
        /// </summary>
        internal static string UserVehicleNotFound {
            get {
                return ResourceManager.GetString("UserVehicleNotFound", resourceCulture);
            }
        }
    }
}
