//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewMobile.Pediddo.Core.Data.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=raul;Initial Catalog=Order;Persist Security Info=True;User ID=Order;P" +
            "assword=Order")]
        public string PediddoConnectionString {
            get {
                return ((string)(this["PediddoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=RENATO-LAPTOP;Initial Catalog=cangoruadb;Integrated Security=True;Con" +
            "nect Timeout=30;Encrypt=False;TrustServerCertificate=True")]
        public string cangoruadbConnectionString1 {
            get {
                return ((string)(this["cangoruadbConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=viewt.database.windows.net,1433;Initial Catalog=Lanovitadb;Persist Se" +
            "curity Info=False;User ID=viewt;Password=Aluno!@$$#SIM466668151!@#$%&&&&;Multipl" +
            "eActiveResultSets=False;Connect Timeout=30;Encrypt=True;TrustServerCertificate=F" +
            "alse")]
        public string cangoruadbConnectionString {
            get {
                return ((string)(this["cangoruadbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=tcp:cangorua.database.windows.net,1433;Initial Catalog=cangoruadb;Persist " +
            "Security Info=False;User ID=cangoruadb;Password=Super163c#podequandojapo2134@;Mu" +
            "ltipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connectio" +
            "n Timeout=30;")]
        public string cangoruadbConnectionString2 {
            get {
                return ((string)(this["cangoruadbConnectionString2"]));
            }
        }
    }
}
